[build]
base = "."
publish = "packages/vega-lite-annotation-playground/dist"
command = "pnpm --filter vega-lite-annotation-playground... build"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--version"
